### ISSUE TITLE
Should we revert to `singleQuotes: true`?

### ISSUE THREAD

**Issue by doup** [mobilejazz/prettier-config#3]
[In the rationale regarding strings](https://prettier.io/docs/en/rationale.html#strings), they mention the following:

> Double or single quotes? Prettier chooses the one which results in the fewest number of escapes. "It's gettin' better!", not 'It\'s gettin\' better!'. In case of a tie or the string not containing any quotes, Prettier defaults to double quotes (but that can be changed via the [singleQuote](https://prettier.io/docs/en/options.html#quotes) option).

So, we could have single quotes, as that wouldn't interfere with this logic; that setting is just a fallback.

On the other hand… you could argue, left it as it is. Let the formatter do its thing…

**Comment by lucianosantana** [comment]
I'd just leave the formatter's default.
